### ISSUE TITLE
Libraray complexity 2 - percentage of duplicated reads in the library

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#113]
1. Calculate statistics

2. Create plot

**Comment by alexg9010** [comment]
https://github.com/BIMSBbioinfo/pigx_chipseq/blob/master/scripts/ChIPQC.R#L169-L172

Read duplication rate right now is actually Proportion of Unique Fragments. 
Should be 1 - Proportion of Unique Fragments.
