### ISSUE TITLE
Check whether the fasta sequence names are the same as gtf sequence names

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#14]
If gtf file is provided, check that they are from the same corresponding organism

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pigx-chipseq bug fixes needed before F1000](https://trello.com/c/uZVSztg1/12-pigx-chipseq-bug-fixes-needed-before-f1000)

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pigx-chipseq: check for matching sequence names in genome and annotation](https://trello.com/c/lnlpyokx/14-pigx-chipseq-check-for-matching-sequence-names-in-genome-and-annotation)

**Comment by alexg9010** [comment]
solved here c5225023258e99776ef34b60665df8c633e447a0
