### ISSUE TITLE
Differential Peak Calling

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#17]
Implement differential peak calling between the samples

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Differential Peak Calling](https://trello.com/c/7ehbdIzo/60-differential-peak-calling)

**Comment by alexg9010** [comment]
borrow ideas from here: 

https://rockefelleruniversity.github.io/RU_ATAC_Workshop.html#greenleaf-dataset---finding-open-regions.

**Comment by alexg9010** [comment]
This was implemented in #155
