### ISSUE TITLE
Make BigWigExtend a streaming function

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#20]
Can be done with BamFile and yield size

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make BigWigExtend a streaming function](https://trello.com/c/LwVROYc1/59-make-bigwigextend-a-streaming-function)

**Comment by alexg9010** [comment]
Fixed with https://github.com/BIMSBbioinfo/pigx_chipseq/pull/95
