### ISSUE TITLE
Per rule target execution

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#27]

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pigx-chipseq bug fixes needed before F1000](https://trello.com/c/uZVSztg1/12-pigx-chipseq-bug-fixes-needed-before-f1000)

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pigx-chipseq bug fixes needed before F1000](https://trello.com/c/uZVSztg1/12-pigx-chipseq-bug-fixes-needed-before-f1000)

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pigx-chipseq: per rule target execution](https://trello.com/c/BmlMRJiI/13-pigx-chipseq-per-rule-target-execution)
