### ISSUE TITLE
Output directory description

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_chipseq#50]
Detailed description of the output directory 
- maybe reformat the output directory to have a better structure

**Comment by alexg9010** [comment]
What do you exactly mean by this? 
Omitting the tool names?
Omitting samples specific folders? 

Or just add a section to the README ?

**Comment by alexg9010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Output directory description](https://trello.com/c/xnemSgTY/49-output-directory-description)
