### ISSUE TITLE
InputError is not defined

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_chipseq#58]
I get this error when I try to run the pipeline with the *yaml* sample sheet from the test data directory, and using the test settings.yaml file:

NameError in line 52 of /gnu/store/x8nzq1adcq56nry5na0gv7zq14h77500-pigx-chipseq-0.0.8/libexec/pigx_chipseq/scripts/SnakeFunctions.py:
name 'InputError' is not defined

**Comment by alexg9010** [comment]
The supported file types of sample sheet are cs, xls or xlsx. 
But I committed a change which should catch this now (https://github.com/BIMSBbioinfo/pigx_chipseq/commit/cb74a35397dc59410e5afb0a5048a3e42ecb0675)

**Comment by rekado** [comment]
Right.  This bug report, however, is not about the fact that it didn't work with a yaml sample sheet, but that the exception itself is undefined.

I never got to see the error, because InputError is undefined.

**Comment by alexg9010** [comment]
Exactly this was addressed ;)

**Comment by rekado** [comment]
Re the change: I think it's better style to avoid an extra level of indentation by checking for the error condition first and aborting right there.  Then you don't have to deal with an else branch.

But that's a minor issue.  I consider this closed as the original error is gone now.

Thanks!
