### ISSUE TITLE
Must have example XLS sample sheet

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_chipseq#59]
We have an init feature, which copies the example data into the current working directory.  It's a feature to make it easier to get started.

For this pipeline we don't have an example XLS sample sheet.  In fact, there is no XLS sample sheet anywhere, so I don't know how to test this.

**Comment by alexg9010** [comment]
I added xls sample_sheet (https://github.com/BIMSBbioinfo/pigx_chipseq/commit/e9b6602acd910bf619657a9f2d1dcad34a9b274e)

**Comment by rekado** [comment]
What is sample_sheet_broken.csv?

Also: would you like to implement the copying of the example sample sheet to the user's current working directory?

**Comment by alexg9010** [comment]
so sample_sheet_broken is a sample_sheet that should bail, do to wrong column names. 
It contains some leading and trailing spaces too, but these are stripped of during parsing. 
Actually it is not important for the pipeline, just for checking. 

Re copying: Did you do this somewhere already in any pipeline?

**Comment by rekado** [comment]
> Re copying: Did you do this somewhere already in any pipeline?

Yes, even in this pipeline: https://github.com/BIMSBbioinfo/pigx_chipseq/blob/master/pigx-chipseq.in#L320

Here's the same thing in rnaseq:
https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/master/pigx-rnaseq.in#L269

**Comment by alexg9010** [comment]
instead of copying the full etc/settings.yaml would it better to add a etc/settings.yaml.example that includes the comments from the README and copy this on init?

**Comment by rekado** [comment]
Then you'd have to maintain two files and keep them in sync.  Experience has shown that this doesn't happen unless it's automated.

We can and should, however, add comments to the etc/settings.yaml.in.

**Comment by alexg9010** [comment]
The reason why I am asking is, that in the etc/settings there is the full configuration contained, while the general user only needs to adjust a subset of these. 
Would it be possible to copy these files from the Tests directory instead? Since this has to work anyway and might be a more realistic abstraction of user provided settings? 

Anyways this could also be a whishlist thing and until then I will just use the files in etc.

**Comment by rekado** [comment]
> The reason why I am asking is, that in the etc/settings there is the full configuration contained, while
> the general user only needs to adjust a subset of these.

That's right, but all of the settings are commented out.

The reason why we show all possible settings keys is that there is no need for guessing.  Everything that is shown there may be modified, including unusual things such as the paths to configured tools.

It is up to the pipeline authors to add comments that indicate the keys that must be modified whereas others may be marked up as for advanced users.

**Comment by alexg9010** [comment]
I see, that actually makes sense. 
okay, then I will add some comments to the default settings.

**Comment by alexg9010** [comment]
addressed with (https://github.com/BIMSBbioinfo/pigx_chipseq/commit/cefb9c480f14d6b60459f28ebfb7a5e0f3faf25d) and (https://github.com/BIMSBbioinfo/pigx_chipseq/commit/3bd0dd86b9398de9284735ad6390ebd5247ff0c0)

**Comment by al2na** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/N5ablA9e/8-test)
