### ISSUE TITLE
Some Gtf files are not supported

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#90]
```
Importing gtf...
Selecting transcripts...
Making union...
Constructing annotation...
Error in `[.data.frame`(as.data.frame(DataFrame(gtf.exon)), , c("gene_id",  : 
  undefined columns selected
Calls: Prepare_Annotation -> ReadGTFAnnotation -> unique -> [ -> [.data.frame
Execution halted
```

**Comment by alexg9010** [comment]
@frenkiboy the issue occurs here: https://github.com/BIMSBbioinfo/pigx_chipseq/blob/b63f38222bd4aa6a4ddaadfa5a83a1dd22f4cb0f/scripts/Functions_Helper.R#L70

The problem is that not all gtf files have the `'gene_name','gene_biotype'` attributes. 
And from the code we are not actually using them.

**Comment by frenkiboy** [comment]
I think you can put set the default column names to gene_id, transcript_id,
gene_name, gene_biotype,
and then do intercsect(default, colnames). That should solve the issue
